// <auto-generated />
using EthanCommunion.API.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EthanCommunion.API.Migrations
{
    [DbContext(typeof(StarsContext))]
    [Migration("20170801042026_EthanCommunionDBAddedInfants")]
    partial class EthanCommunionDBAddedInfants
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-preview2-25794")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EthanCommunion.API.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddressLine1");

                    b.Property<string>("AddressLine2");

                    b.Property<string>("Country");

                    b.Property<string>("Postcode");

                    b.Property<int>("StarId");

                    b.Property<string>("State");

                    b.HasKey("Id");

                    b.HasIndex("StarId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("EthanCommunion.API.Entities.Star", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Adults");

                    b.Property<int>("Children");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<int>("Infant");

                    b.Property<string>("LastName");

                    b.Property<string>("Mobile");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Star");
                });

            modelBuilder.Entity("EthanCommunion.API.Entities.Address", b =>
                {
                    b.HasOne("EthanCommunion.API.Entities.Star", "Star")
                        .WithMany("Addresses")
                        .HasForeignKey("StarId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
